server:
  port: 8081
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8

spring:
  # Mysql配置
  datasource:
    url: jdbc:mysql://localhost:3306/ialcohol?useInformationSchema=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
